# Generated by Django 4.0 on 2022-10-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_hajiri', '0002_faceverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=64)),
                ('attendee_id', models.UUIDField()),
                ('device', models.CharField(max_length=64)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
