# Generated by Django 4.0 on 2022-10-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_hajiri', '0003_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
