# Generated by Django 4.0 on 2022-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_hajiri', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
